name: Qt6xInstall
on:
  push:
    branches: 
      - dev
      - main
      - master
jobs:
  Build_Focus_App:
    runs-on: macos-latest
    steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              repository: 'Cybercraft-llc/Eyeguide'
              set-safe-directory: '${{ github.workspace }}/dev'
              ref: 'dev'
              token: ${{ secrets.PAT_TOKEN_REPO }}
          - name: Install Qt for mac.
            run: |
              python3 -m pip install aqtinstall==3.1.*
              aqt install-qt mac desktop 6.4.2 clang_64
          - name: Install Qt for iOS.
            uses: jurplel/install-qt-action@v3
            with:
              aqtversion: '==3.1.*'
              py7zrversion: '>=0.20.2'
              version: '6.4.2'
              host: 'mac'
              target: 'ios'
              arch: 'ios'
              dir: '${{ github.workspace }}/qtInstall/'
              modules: 'qt3d qtcharts qtconnectivity qtdatavis3d qthttpserver qtimageformats qtlottie qtmultimedia qtnetworkauth qtpdf qtpositioning qtquick3dphysics qtremoteobjects qtscxml qtsensors qtserialbus qtspeech qtvirtualkeyboard qtwebchannel qtwebsockets qtwebview qt5compat qtquick3d qtquicktimeline qtshadertools'
          - name: Running Cmake.
            run: 'cmake -GXcode -DCMAKE_BUILD_TYPE=Release -DAPPLE_IOS_TARGET=True -DAPPLE_IOS_DEVICE=True -DMIN_IOS_SDK_TARGET=13 -DQT_HOST_PATH=${{ github.workspace }}/qtInstall/Qt/6.4.2/macos -DQT_SDK_DIR=${{ github.workspace }}/qtInstall/Qt/6.4.2/ios -DCMAKE_TOOLCHAIN_FILE=CMake/Cute.toolchain.cmake -H. -Bbuild'
          - name: Running XCode.
            run: echo "running Xcode."

